name: Tries this action

on: push

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          event: ${{ toJson(github.event) }}
          apiToken: ${{ secrets.API_TOKEN }}
          apiUrl: ${{ secrets.API_URL }}
          providers: ${{ secrets.PROVIDERS }}
          refName: ${{ github.ref_name }}
